### ISSUE TITLE
PicoTCP revision hash is incorrect

### ISSUE THREAD

**Issue by JohnAZoidberg** [seL4/camkes-vm-manifest#3]
When I `init` and `sync` the repo, it tells me that the revision hash of picotcp is incorrect.
Are the instructions [here](https://docs.sel4.systems/Hardware/Qemu/) still correct?

Here's are the commands I ran and their output:
```
$ repo init -u https://github.com/seL4/camkes-vm-manifest.git
$ repo sync
Fetching project picotcp.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
remote: Enumerating objects: 22083, done.
remote: Total 22083 (delta 0), reused 0 (delta 0), pack-reused 22083
Receiving objects: 100% (22083/22083), 10.45 MiB | 10.37 MiB/s, done.
Resolving deltas: 100% (16137/16137), done.
From https://github.com/SEL4PROJ/picotcp
 * [new branch]        6LoWPAN                     -> SEL4PROJ/6LoWPAN
 * [new branch]        6LoWPAN_dev                 -> SEL4PROJ/6LoWPAN_dev
 * [new branch]        amalgamation_dev            -> SEL4PROJ/amalgamation_dev
 * [new branch]        aos-2018                    -> SEL4PROJ/aos-2018
 * [new branch]        dev-dhcp6                   -> SEL4PROJ/dev-dhcp6
 * [new branch]        dev-esp8266                 -> SEL4PROJ/dev-esp8266
 * [new branch]        dev_fuzzer_malloc           -> SEL4PROJ/dev_fuzzer_malloc
 * [new branch]        dev_heap_insert             -> SEL4PROJ/dev_heap_insert
 * [new branch]        dev_pmtu                    -> SEL4PROJ/dev_pmtu
 * [new branch]        dev_ppp                     -> SEL4PROJ/dev_ppp
 * [new branch]        dev_sntp                    -> SEL4PROJ/dev_sntp
 * [new branch]        dev_tests                   -> SEL4PROJ/dev_tests
 * [new branch]        development                 -> SEL4PROJ/development
 * [new branch]        heap_blocks                 -> SEL4PROJ/heap_blocks
 * [new branch]        master                      -> SEL4PROJ/master
 * [new branch]        mdns_wip                    -> SEL4PROJ/mdns_wip
 * [new branch]        nastybugs                   -> SEL4PROJ/nastybugs
 * [new branch]        picoMESH                    -> SEL4PROJ/picoMESH
 * [new branch]        pico_changes_pareon         -> SEL4PROJ/pico_changes_pareon
 * [new branch]        ppp_350                     -> SEL4PROJ/ppp_350
 * [new branch]        prpl                        -> SEL4PROJ/prpl
 * [new branch]        safe-pico                   -> SEL4PROJ/safe-pico
 * [new branch]        tahi                        -> SEL4PROJ/tahi
 * [new branch]        tahi_fix                    -> SEL4PROJ/tahi_fix
 * [new branch]        thos                        -> SEL4PROJ/thos
 * [new branch]        tickless                    -> SEL4PROJ/tickless
 * [new branch]        tics_experiment             -> SEL4PROJ/tics_experiment
 * [new branch]        zmqdev                      -> SEL4PROJ/zmqdev
 * [new tag]           V1.0                        -> V1.0
 * [new tag]           V1.2.4                      -> V1.2.4
 * [new tag]           aos-2018                    -> aos-2018
 * [new tag]           prpl-v0.1                   -> prpl-v0.1
 * [new tag]           sprint0                     -> sprint0
 * [new tag]           sprint1                     -> sprint1
 * [new tag]           sprint2                     -> sprint2
 * [new tag]           sprint3                     -> sprint3
 * [new tag]           sprint4                     -> sprint4
 * [new tag]           sprint5                     -> sprint5
 * [new tag]           sprint6                     -> sprint6
 * [new tag]           sprint7                     -> sprint7
 * [new tag]           sprint8                     -> sprint8
 * [new tag]           v1.1-rc1                    -> v1.1-rc1
 * [new tag]           v1.2                        -> v1.2
 * [new tag]           v1.2.1                      -> v1.2.1
 * [new tag]           v1.2.2                      -> v1.2.2
 * [new tag]           v1.2.3                      -> v1.2.3
 * [new tag]           v1.3.0                      -> v1.3.0
 * [new tag]           v1.4.0                      -> v1.4.0
 * [new tag]           v1.4.1-dev-customer-sprint1 -> v1.4.1-dev-customer-sprint1
 * [new tag]           v1.4.2                      -> v1.4.2
 * [new tag]           v1.5.0                      -> v1.5.0
 * [new tag]           v1.5.1                      -> v1.5.1
 * [new tag]           v1.6.0                      -> v1.6.0
 * [new tag]           v1.6.1                      -> v1.6.1
 * [new tag]           v1.6.2                      -> v1.6.2
 * [new tag]           v1.7.0                      -> v1.7.0
error: Cannot fetch picotcp.git (GitError: picotcp.git update-ref: fatal: 7f12f2949f44b1de04e9d89407642a9efee878c6^0: not a valid SHA1
)
Traceback (most recent call last):
  File "/home/zoid/clone/sel4test/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/home/zoid/clone/sel4test/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/home/zoid/clone/sel4test/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/zoid/clone/sel4test/.repo/repo/subcmds/sync.py", line 781, in Execute
    fetched = self._Fetch(to_fetch, opt)
  File "/home/zoid/clone/sel4test/.repo/repo/subcmds/sync.py", line 381, in _Fetch
    self._FetchProjectList(**kwargs)
  File "/home/zoid/clone/sel4test/.repo/repo/subcmds/sync.py", line 270, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/zoid/clone/sel4test/.repo/repo/subcmds/sync.py", line 314, in _FetchHelper
    prune=opt.prune)
  File "/home/zoid/clone/sel4test/.repo/repo/project.py", line 1271, in Sync_NetworkHalf
    self._InitMRef()
  File "/home/zoid/clone/sel4test/.repo/repo/project.py", line 2364, in _InitMRef
    self._InitAnyMRef(R_M + self.manifest.branch)
  File "/home/zoid/clone/sel4test/.repo/repo/project.py", line 2376, in _InitAnyMRef
    self.bare_git.UpdateRef(ref, dst, message=msg, detach=True)
  File "/home/zoid/clone/sel4test/.repo/repo/project.py", line 2673, in UpdateRef
    self.update_ref(*cmdv)
  File "/home/zoid/clone/sel4test/.repo/repo/project.py", line 2747, in runner
    (self._project.name, name, p.stderr))
error.GitError: picotcp.git update-ref: fatal: 7f12f2949f44b1de04e9d89407642a9efee878c6^0: not a valid SHA1
```

**Comment by kent-mcleod** [comment]
Hi,
That page is a bit outdated and many of the instructions are incorrect. I opened an issue to update it here: https://github.com/SEL4PROJ/docs/issues/20
Depending on what you want to do, there are other pages which may have the information:
- Running camkes-vm projects: https://docs.sel4.systems/CAmkESVM
- Simulating seL4 x86 VM projects: https://docs.sel4.systems/Tutorials/camkes-vm-linux.html#background
- Projects that don't use VTX extensions can be simulated by running ./simulate in the build directory. This works on the projects: sel4test, sel4bench, camkes, rumprun-sel4-demoapps. For other projects that aren't maintained by us, the simulation script can be generated by adding `GenerateSimulateScript()` to the project's CMakeLists.txt file.
- Check out a version of picotcp that works on seL4: We now use an upstream version: https://github.com/seL4/camkes-vm-examples-manifest/blob/master/default.xml#L35

**Comment by lsf37** [comment]
The sha1 does actually still exist in the pico-tcp repository, but is not on any branch, so will not be cloned automatically. I'll attempt to fix that so that the last working checkout state can be recreated, but otherwise this repo will be archived shortly.
